spring:
  application:
    name: reader-app
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: conduktor
    password: change_me
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
server:
  port: 3333

logging:
  level:
    org: INFO
    tracer: TRACE